import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { discoverVersions, generateRegistry, renderRegistry } from '../src/generate-registry.js';
import { MERIDIAN_DIR, ensureStateDir } from '../src/lib/state.js';

/**
 * The registry generator.
 *
 * The property that matters is not the formatting but the shape: every registered version has to
 * be reachable through a **top-level import statement**. The registry is bundled into the Temporal
 * workflow sandbox, where dynamic `import()` and directory reads do not exist, so a generator that
 * emitted a lazy loader would produce a file that type-checks, passes review, and fails only at
 * workflow-execution time.
 */

const scratchDirs: string[] = [];

function scratch(): string {
  ensureStateDir();
  const dir = mkdtempSync(join(MERIDIAN_DIR, 'registry-fixture-'));
  scratchDirs.push(dir);
  return dir;
}

function agentVersion(root: string, deploymentKey: string, dirName: string): void {
  const dir = join(root, deploymentKey, dirName);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'agent.ts'), 'export const agent = {};\n');
}

afterEach(() => {
  while (scratchDirs.length > 0)
    rmSync(scratchDirs.pop() as string, { recursive: true, force: true });
});

describe('registry generation', () => {
  it('discovers only directories named vNNN', () => {
    const root = scratch();
    agentVersion(root, 'inbound-import-receiving', 'v001');
    agentVersion(root, 'inbound-import-receiving', 'v002');
    agentVersion(root, 'inbound-import-receiving', 'draft');
    agentVersion(root, 'inbound-import-receiving', 'v1');
    mkdirSync(join(root, 'node_modules', 'v001'), { recursive: true });

    const found = discoverVersions(root);
    expect(found.map((version) => `${version.deploymentKey}@${version.versionNo}`)).toEqual([
      'inbound-import-receiving@1',
      'inbound-import-receiving@2',
    ]);
  });

  it('emits a top-level import per version and a static map', () => {
    const root = scratch();
    agentVersion(root, 'inbound-import-receiving', 'v001');
    agentVersion(root, 'outbound-export-booking', 'v003');

    const rendered = renderRegistry(discoverVersions(root));
    expect(rendered).toContain(
      "import { agent as inboundImportReceivingV001 } from './inbound-import-receiving/v001/agent.js';",
    );
    expect(rendered).toContain(
      "import { agent as outboundExportBookingV003 } from './outbound-export-booking/v003/agent.js';",
    );
    expect(rendered).toContain("'inbound-import-receiving': {");
    expect(rendered).toContain('3: outboundExportBookingV003,');

    // The two constructs that would break inside the workflow sandbox must not appear in the code.
    // The doc comment is stripped first: it names `import()` in order to explain why the generated
    // code does not use it.
    const code = rendered.replace(/\/\*\*[\s\S]*?\*\//g, '');
    expect(code).not.toMatch(/\bimport\(/);
    expect(code).not.toMatch(/readdirSync|require\(/);
  });

  it('renders an empty but valid registry when nothing is generated yet', () => {
    const rendered = renderRegistry([]);
    expect(rendered).toContain(
      'export const AGENT_REGISTRY = {} as const satisfies AgentRegistry;',
    );
  });

  it('writes only when the content actually changed', () => {
    const root = scratch();
    agentVersion(root, 'inbound-import-receiving', 'v001');

    const first = generateRegistry(root);
    expect(first.changed).toBe(true);
    const written = readFileSync(first.outPath, 'utf8');

    const second = generateRegistry(root);
    expect(second.changed).toBe(false);
    expect(readFileSync(second.outPath, 'utf8')).toBe(written);

    agentVersion(root, 'inbound-import-receiving', 'v002');
    expect(generateRegistry(root).changed).toBe(true);
  });

  it('matches the registry checked into this repository', () => {
    // The committed registry is generated by this function. If regenerating it would change the
    // file, the worker is bundling a different set of agents than the tree claims.
    const committed = readFileSync(
      new URL('../../../generated-agents/index.ts', import.meta.url),
      'utf8',
    );
    const root = new URL('../../../generated-agents/', import.meta.url).pathname;
    expect(renderRegistry(discoverVersions(root))).toBe(committed);
  });
});
